# Generated by Django 4.2 on 2024-12-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Menu Item Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('MAIN_COURSE', 'Main Course'), ('DESSERT', 'Dessert'), ('BEVERAGE', 'Beverage'), ('SIDE', 'Side')], max_length=20, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price (KSH)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Item Image')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
