# Generated by Django 4.2 on 2024-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0002_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('people', models.IntegerField()),
                ('requests', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
