# Generated by Django 4.2 on 2024-12-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0006_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='people',
        ),
    ]
