# Generated by Django 4.2 on 2024-12-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0007_delete_member_delete_room_remove_reservation_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.CharField(default='Standard Room', max_length=100),
        ),
    ]
