# Generated by Django 4.2 on 2024-12-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0009_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='datetime',
            new_name='date',
        ),
    ]
