# Generated by Django 4.2 on 2024-12-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0010_rename_datetime_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
