# Generated by Django 4.2 on 2024-12-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0013_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='imagemodel',
            name='twitter_link',
        ),
    ]
