# Generated by Django 4.2 on 2024-12-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0014_remove_imagemodel_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
