# Generated by Django 4.2 on 2024-12-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0016_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cana',
        ),
    ]
