# Generated by Django 4.2 on 2024-12-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canaapp', '0018_cana_delete_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Cana',
        ),
    ]
